image: "ubuntu:22.04"
additional_volumes:
  - "/etc/passwd:/etc/passwd:ro"
  - "/etc/group:/etc/group:ro"
  - "/etc/shadow:/etc/shadow:ro"
  - "/etc/locale.conf:/etc/locale.conf"

ssh_agent:
  host: ""
  key_path: ""

user_config:
  entrypoint: ["/bin/bash"]
