image: "ubuntu:22.04"
additional_volumes:
  - "~/.devops-toolbox/kube:~/.kube"
  - "~/.devops-toolbox/.terraformrc:~/.terraformrc"

ssh_agent:
  host: ""
  key_path: ""

user_config:
  entrypoint: ["/bin/bash"]
