#entrypoint: ["bash", "-c", "while true; do bash || true; done"]
#entrypoint: ["bash", "-c", "bash $HOME/.startup.sh"]

home_volumes:
  - '.admin-toolbox/ssh:.ssh'
#  - '.admin-toolbox/startup.sh:.startup.sh'

env:
  - TEST="HEY"
